# -*- coding: utf-8 -*-
"""citations.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tBjNZKiw_3eufs35OLENhr6pdQ8J8id_
"""

!pip install uv
!uv pip install  'llama-index-llms-huggingface' 'llama-index-embeddings-huggingface' 'llama-index-vector-stores-chroma' 'setuptools' 'mamba-ssm'
!uv pip install -U protobuf

from transformers import AutoTokenizer, AutoModelForCausalLM
from llama_index.core.llms import ChatMessage
from llama_index.llms.huggingface import HuggingFaceLLM

from llama_index.core import Settings

# model_name = "nvidia/Nemotron-Cascade-2-30B-A3B"
# model_name = "chankhavu/Nemotron-Cascade-2-30B-A3B-FP8"
model_name = "NousResearch/DeepHermes-3-Llama-3-8B-Preview"

tokenizer = AutoTokenizer.from_pretrained(model_name, device_map='auto' )
model = AutoModelForCausalLM.from_pretrained(model_name, device_map='auto')


llm = HuggingFaceLLM(tokenizer=tokenizer, model=model, device_map='auto')

Settings.llm = llm

from llama_index.embeddings.huggingface import HuggingFaceEmbedding

embed_model = HuggingFaceEmbedding(model_name="perplexity-ai/pplx-embed-v1-0.6b", trust_remote_code=True)
Settings.embed_model = embed_model

from datasets import load_dataset

dataset = load_dataset('rajpurkar/squad')
print(dataset)

import chromadb
from llama_index.vector_stores.chroma import ChromaVectorStore
from llama_index.core import VectorStoreIndex, StorageContext, Document


# Creating a Chroma client
# EphemeralClient operates purely in-memory, PersistentClient will also save to disk
chroma_client = chromadb.EphemeralClient()
chroma_collection = chroma_client.create_collection("quickstart")

# construct vector store
vector_store = ChromaVectorStore(
    chroma_collection=chroma_collection,
)

storage_context = StorageContext.from_defaults(vector_store=vector_store)

"""Next, we'll prepare some documents from the loaded `squad` dataset and create an index. For simplicity, we'll take a small subset of the training data."""

# Assuming 'dataset' is already loaded from 'rajpurkar/squad'
# If not, uncomment the line below:
# from datasets import load_dataset
# dataset = load_dataset('rajpurkar/squad')

# Create LlamaIndex Documents from the dataset
documents = []
for i, example in enumerate(dataset['train'].select(range(1000))): # Using a subset for quick demo
    documents.append(Document(text=example['context'], metadata={'id': example['id'], 'title': example['title']}))

# Create the index
index = VectorStoreIndex.from_documents(documents, storage_context=storage_context, embed_model=embed_model)
print("ChromaDB index created successfully with 1000 documents!")

query_engine = index.as_query_engine(llm = llm, embed_model=embed_model)
response = query_engine.query("What is the Grotto at Notre Dame?")
print(response)

index.as_retriever().retrieve("What is the Grotto at Notre Dame?")

response

Settings.llm

llm.complete("hello, what is your name?")

